framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false
    handle_all_throwables: true
    php_errors:
        log: true

    # Session configuration for form login
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
    rate_limiter:
        api_submit:
            policy: 'sliding_window'
            limit: 10
            interval: '1 minute'
            cache_pool: cache.app

when@test:
    framework:
        rate_limiter:
            api_submit:
                policy: 'no_limit'
